### ISSUE TITLE
IOError: [Errno 21] Is a directory: '/Users/heping/Documents/objc4/./..'

### ISSUE THREAD

**Issue by MemoryReload** [mythkiven/mkAppleOpenSourceDownload#2]
```
[heping@Laputa:~/Documents]$aosdownload 'objc'
>> Search keyword: objc..
>> Match to resource:[objc4], will download
>> --> Download from  "https://opensource.apple.com/" <--
>>> Download : ./..
Traceback (most recent call last):
  File "/Users/heping/.pyenv/versions/2.7.14/bin/aosdownload", line 22, in <module>
    main()
  File "/Users/heping/.pyenv/versions/2.7.14/bin/aosdownload", line 18, in main
    mkADownload().download(word=args.text, path=args.save_path)
  File "/Users/heping/.pyenv/versions/2.7.14/lib/python2.7/site-packages/mkAppleOpenSourceDownload/download.py", line 91, in download
    self.downloadTarWithURL(href , os.path.join(path,title))
  File "/Users/heping/.pyenv/versions/2.7.14/lib/python2.7/site-packages/mkAppleOpenSourceDownload/download.py", line 95, in downloadTarWithURL
    f = open(path, 'wb')
IOError: [Errno 21] Is a directory: '/Users/heping/Documents/objc4/./..'
```

**Comment by MemoryReload** [comment]
we should change this line:
```
if(href == './../'):
                continue
```
to 

```
if(string.find(href,'./..')==0):
                continue
```
or things will go wrong.

**Comment by mythkiven** [comment]
@MemoryReload 感谢反馈，也感谢你给出的修复建议 👍

**原因**

下载 `objc4` 时，Apple 开源站目录页里除了 `../` 返回上级目录外，还存在 `./..` 这类相对路径链接。当前代码只过滤了完全等于 `'./../'` 的情况：

```python
if(href == './../'):
    continue
```

而实际页面返回的是 `./..`（少了末尾 `/`），导致被当成 tar 包下载，最终 `open(path, 'wb')` 时路径指向目录，触发 `IOError: [Errno 21] Is a directory`。

**修复方案**

你的建议是对的，改为前缀匹配即可：

```python
if href.startswith('./..'):
    continue
```

两处循环（搜索列表 + 下载列表）都需要改。

**临时 workaround**

在官方修复发布前，可以手动指定下载目录并跳过异常链接，或 clone 仓库后本地改 `download.py` 再安装：

```bash
git clone https://github.com/mythkiven/mkAppleOpenSourceDownload.git
cd mkAppleOpenSourceDownload
# 修改 mkAppleOpenSourceDownload/download.py 中两处 href 判断
pip install -e .
aosdownload objc -p ~/runtime
```

**后续**

会在下一版修复并发布到 PyPI。另外也注意到 Apple 已将部分开源资源迁移，若遇到 404 或页面结构变化，欢迎继续反馈 🙏

**Comment by mythkiven** [comment]
已在 master 修复并发布 v1.5 代码：

- 过滤 `./..` 等父目录链接，避免 `IOError: Is a directory`
- 同时跳过目录型 href（以 `/` 结尾）

```bash
pip install --upgrade mkAppleOpenSourceDownload
```

如仍有问题欢迎继续反馈 🙏

**Comment by mythkiven** [comment]
已在 v1.5.1 通过 `should_skip_href()` 过滤 `./..` 与目录链接，避免 IOError。关闭 issue。
